d3.select("#header")
    .append("a")
        .attr("id", "header-title")

d3.select("#header-title")
    .append("div")
        .text("Transformer Explainer")

d3.select("#header")
    .append("div")
    .attr("id", "header-message")

d3.select("#header-message")
    .append("div")
        .attr("id", "header-message-1")
        .text("Learn how transformer architecture revolutionized language modeling!")

d3.select("#header")
    .append("div")
    .attr("id", "header-links")

d3.select("#header-links")
    .append("a")
        .attr("class", "header-link")
        .attr("id", "header-link-github")
        .attr("href", "https://github.com/mathadoor/TransformerExposition")
        .append("img")
            .attr("id", "header-link-img-github")
            .attr("class", "header-link-img")
            .attr("src", "./icons/github.svg")
d3.select("#header-link-github")
    .append("div")
        .attr("id", "header-link-text-github")
        .attr("class", "header-link-text")
        .text("Code")

d3.select("#header-links")
    .append("a")
        .attr("class", "header-link")
        .attr("id", "header-link-youtube")
        // .attr("href", "https://youtu.be/Zg4gxdIWDds")
        .append("img")
            .attr("id", "header-link-img-youtube")
            .attr("class", "header-link-img")
            .attr("src", "./icons/youtube.svg")

d3.select("#header-link-youtube")
    .append("div")
        .attr("id", "header-link-text-youtube")
        .attr("class", "header-link-text")
        .text("Video")